# keep the strict reverse path filtering
# if there are problems with the routing, try 2 first to narrow down the cause
net.ipv4.conf.all.rp_filter=1
# we want to log all martians, they are a symptom for asymmetric routing
net.ipv4.conf.eth0.log_martians=1
net.ipv4.conf.eth1.log_martians=1
# we need this in order to have the kernel consider the fwmark when calculating 
# the reverse path
net.ipv4.conf.eth0.src_valid_mark=1
# the reserved range of ports for the passive connections. the line will be replaced
# dynamically from the aeroslot service
net.ipv4.ip_local_reserved_ports = 20000-49999
