[agent]
  collection_jitter = "0s"
  debug = false
  flush_interval = "1s"
  flush_jitter = "0s"
  hostname = ""
  interval = "60s"
  logfile = "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
  logtarget = "lumberjack"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = false
  precision = ""
  quiet = false
  round_interval = false
  run_as_user = "root"

[inputs]

  [[inputs.logfile]]
    destination = "cloudwatchlogs"
    file_state_folder = "/opt/aws/amazon-cloudwatch-agent/logs/state"

    [[inputs.logfile.file_config]]
      deployment_environment = ""
      file_path = "/var/log/aeroftp/aeroftp.log"
      from_beginning = true
      log_group_class = ""
      log_group_name = "/aeroftp/backend"
      log_stream_name = "$INSTANCE_ID"
      pipe = false
      retention_in_days = -1
      service_name = ""
      timestamp_layout = ["2006-01-_2T15:04:05", "2006-1-_2T15:04:05"]
      timestamp_regex = "(\\d{4}-\\s{0,1}\\d{1,2}-\\s{0,1}\\d{1,2}T\\d{2}:\\d{2}:\\d{2})"
      timezone = "UTC"

[outputs]

  [[outputs.cloudwatchlogs]]
    force_flush_interval = "5s"
    log_stream_name = "$INSTANCE_ID"
    mode = "EC2"
    region = "eu-west-2"
    region_type = "ACJ"

